name: projet_court_transmembranaire
channels:
    - conda-forge
    - salilab
    - nodefaults
dependencies:
    - python
    - biopython
    - numpy
    - scipy
    - matplotlib
    - pandas
    - jupyterlab
    - mdanalysis
    - dssp
